/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// void free(void *ptr);
// size_t fread(void *ptr, size_t size, size_t n, FILE *stream);
// size_t strlen(const char *s);
// char *strchr(const char *s, int c);
// int printf(const char *format, ...);
// void *memcpy(void *dest, const void *src, size_t n);
// void *malloc(size_t size);
// int fflush(FILE *stream);
// void *realloc(void *ptr, size_t size);
// void *memmove(void *dest, const void *src, size_t n);
// FILE *fopen(const char *filename, const char *modes);
// void perror(const char *s);
// void __noreturn exit(int status);
// const unsigned __int16 **__ctype_b_loc(void);
void __noreturn cstrasstr_cold();
void __noreturn stralloc_cold();
int __fastcall main(int argc, const char **argv, const char **envp);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
FILE **deregister_tm_clones();
__int64 register_tm_clones();
FILE **_do_global_dtors_aux();
__int64 frame_dummy(); // weak
size_t *__fastcall cstrasstr(size_t *a1, const char *a2);
size_t *__fastcall stralloc(size_t *a1, size_t a2);
unsigned __int64 __fastcall straddc(unsigned __int64 *a1, char a2);
void __fastcall straddcs(_QWORD *a1, char *a2);
void __fastcall stradds(_QWORD *a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, int a7, int a8, char *a9);
void __fastcall strfree(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, void *ptr);
__int64 __fastcall strascstr(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, int a7, int a8, __int64 a9);
void *__fastcall _base_vec_push(void **a1, __int64 *a2, __int64 *a3, size_t a4, const void *a5);
__int64 __fastcall _base_vec_pop(__int64 a1, __int64 *a2, __int64 a3);
void *__fastcall _base_vec_insert(void **a1, unsigned __int64 *a2, __int64 *a3, size_t a4, const void *a5, unsigned __int64 a6);
__int64 __fastcall _base_vec_at(_QWORD *a1, unsigned __int64 *a2, unsigned __int64 a3, __int64 a4);
void __fastcall _base_vec_free(void **a1, _QWORD *a2, _QWORD *a3);
bool __fastcall issep(char a1);
bool __fastcall isop(char a1);
__int64 __fastcall isword(char a1);
_BOOL8 __fastcall isnumber(char a1);
bool __fastcall isnewline(char a1);
__int64 __fastcall iswhitespace(char a1);
bool __fastcall iscomment(char a1);
bool __fastcall isnotquote(char a1);
bool __fastcall isnotnewline(char a1);
__int64 __fastcall exhaust(__int64 a1, __m128i *a2, unsigned __int64 *a3, __int64 (__fastcall *a4)(_QWORD), int a5, __int64 a6, int a7, unsigned __int64 a8, __int64 a9);
__int64 __fastcall next_token(__int64 a1, unsigned __int64 *a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, int a7, unsigned __int64 a8, __int64 a9);
bool __fastcall isinstsplit(char a1);
bool __fastcall isopsplit(char a1);
void __fastcall skip_whitespace(__int64 a1, __int64 *a2, _BYTE *a3);
unsigned __int64 __fastcall skip_until_newline(__int64 a1, unsigned __int64 *a2);
unsigned __int64 *__fastcall collect_symbol(__int64 a1, unsigned __int64 *a2, _BYTE *a3);
__int64 __fastcall next_inst(__int64 a1, __int64 a2, __int64 a3);
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int _cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak
// __int64 ITM_registerTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int128 xmmword_3270 = 0x6920656D20706C656820657361656C70LL; // weak
void *_dso_handle = &_dso_handle; // idb
FILE *stdout; // idb
char completed_0; // weak


//----- (0000000000001000) ----------------------------------------------------
// Alternative name is '_init'
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ != nullptr )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 5130: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001140) ----------------------------------------------------
void __noreturn cstrasstr_cold()
{
  perror("stralloc, ptr allocation failed");
  exit(1);
}

//----- (0000000000001156) ----------------------------------------------------
void __noreturn stralloc_cold()
{
  perror("stralloc, ptr allocation failed");
  exit(1);
}

//----- (0000000000001170) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  __int64 v3; // rbp
  FILE *v4; // rbx
  __int64 v5; // rdx
  __int64 v6; // rcx
  __int64 v7; // r8
  __int64 v8; // r9
  __int64 v9; // rdx
  __int64 v10; // rcx
  __int64 v11; // r8
  __int64 v12; // r9
  __m128i v13; // xmm0
  __int64 v14; // rcx
  __int64 v15; // rdi
  __int64 v16; // rsi
  __int64 v17; // r8
  __int64 v18; // r9
  char *v19; // rdx
  unsigned int *v20; // rbx
  unsigned __int64 v21; // rax
  __m128i v22; // xmm0
  const char *v23; // rax
  __m128i v25; // [rsp+0h] [rbp-4F8h]
  __m128i v26; // [rsp+0h] [rbp-4F8h]
  __m128i v27; // [rsp+20h] [rbp-4D8h] BYREF
  __m128i v28; // [rsp+30h] [rbp-4C8h] BYREF
  unsigned __int64 v29; // [rsp+48h] [rbp-4B0h] BYREF
  __m128i v30; // [rsp+50h] [rbp-4A8h] BYREF
  __int64 v31; // [rsp+60h] [rbp-498h]
  __int128 v32; // [rsp+70h] [rbp-488h] BYREF
  char *v33; // [rsp+80h] [rbp-478h] BYREF
  _QWORD v34[4]; // [rsp+90h] [rbp-468h] BYREF
  __m128i si128; // [rsp+B0h] [rbp-448h] BYREF
  __int64 v36; // [rsp+C0h] [rbp-438h]
  char ptr[1032]; // [rsp+D0h] [rbp-428h] BYREF
  unsigned __int64 v38; // [rsp+4D8h] [rbp-20h]
  __int64 v39; // [rsp+4F0h] [rbp-8h]

  v38 = __readfsqword(0x28u);
  stralloc((size_t *)&v30, 0x80u);
  v4 = fopen("./playground/mov.asm", "r");
  while ( fread(ptr, 1u, 0x400u, v4) != 0 )
    straddcs(&v30, ptr);
  v29 = 0;
  v32 = 0;
  v33 = nullptr;
  v25 = _mm_load_si128(&v30);
  next_token((__int64)v34, &v29, v5, v6, v7, v8, v25.m128i_i32[0], v25.m128i_u64[1], v31);
  if ( LODWORD(v34[0]) != 8 )
  {
    do
    {
      _base_vec_push((void **)&v33, (__int64 *)&v32 + 1, (__int64 *)&v32, 0x20u, v34);
      v26 = _mm_load_si128(&v30);
      next_token((__int64)&v27, &v29, v9, v10, v11, v12, v26.m128i_i32[0], v26.m128i_u64[1], v31);
      v13 = _mm_loadu_si128(&v28);
      *(__m128i *)v34 = _mm_loadu_si128(&v27);
      *(__m128i *)&v34[2] = v13;
    }
    while ( v27.m128i_i32[0] != 8 );
  }
  v36 = 0x6775626564206ELL;
  si128 = _mm_load_si128((const __m128i *)&xmmword_3270);
  printf("%s", si128.m128i_i8);
  fflush(stdout);
  v19 = v33;
  v20 = (unsigned int *)v33;
  if ( v33 != nullptr )
  {
    v3 = 321;
    while ( v20 < (unsigned int *)&v19[32 * *((_QWORD *)&v32 + 1)] )
    {
      v21 = *v20;
      if ( (unsigned int)v21 <= 8 && _bittest64(&v3, v21) )
      {
        v20 += 8;
        if ( v19 == nullptr )
          break;
      }
      else
      {
        v22 = _mm_loadu_si128((const __m128i *)(v20 + 2));
        v20 += 8;
        v23 = (const char *)strascstr(
                              v15,
                              v16,
                              (__int64)v19,
                              v14,
                              v17,
                              v18,
                              v22.m128i_i32[0],
                              v22.m128i_i32[2],
                              *((_QWORD *)v20 - 1));
        printf("[%s] `%s`@%d: %d: %s\n", "INFO", "src/main.c", 35, *(v20 - 8), v23);
        v19 = v33;
        if ( v33 == nullptr )
          break;
      }
    }
  }
  if ( v38 != __readfsqword(0x28u) )
    v39 = v3;
  return 0;
}
// 1234: variable 'v5' is possibly undefined
// 1234: variable 'v6' is possibly undefined
// 1234: variable 'v7' is possibly undefined
// 1234: variable 'v8' is possibly undefined
// 1290: variable 'v9' is possibly undefined
// 1290: variable 'v10' is possibly undefined
// 1290: variable 'v11' is possibly undefined
// 1290: variable 'v12' is possibly undefined
// 1361: variable 'v15' is possibly undefined
// 1361: variable 'v16' is possibly undefined
// 1361: variable 'v14' is possibly undefined
// 1361: variable 'v17' is possibly undefined
// 1361: variable 'v18' is possibly undefined
// 13C9: variable 'v3' is possibly undefined
// 3270: using guessed type __int128 xmmword_3270;

//----- (00000000000013E0) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, nullptr, nullptr, a3, &v5);
  __halt();
}
// 13EA: positive sp value 8 has been found
// 13F1: variable 'v3' is possibly undefined

//----- (0000000000001410) ----------------------------------------------------
FILE **deregister_tm_clones()
{
  return &stdout;
}
// 5128: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000001440) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}
// 5138: using guessed type __int64 ITM_registerTMCloneTable(void);

//----- (0000000000001480) ----------------------------------------------------
FILE **_do_global_dtors_aux()
{
  FILE **result; // rax

  if ( completed_0 == 0 )
  {
    if ( &_cxa_finalize != nullptr )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 5090: using guessed type char completed_0;

//----- (00000000000014D0) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 14D0: using guessed type __int64 frame_dummy();

//----- (0000000000001500) ----------------------------------------------------
size_t *__fastcall cstrasstr(size_t *a1, const char *a2)
{
  size_t v4; // r13
  _BYTE *v5; // rax
  char v6; // bp
  _BYTE *v7; // rdi
  size_t i; // rbx

  v4 = strlen(a2) + 1;
  v5 = malloc(v4);
  if ( v5 == nullptr )
    cstrasstr_cold();
  v6 = *a2;
  v7 = v5;
  for ( i = 0; v6 != 0; v7[i] = 0 )
  {
    if ( i + 2 >= v4 )
    {
      v4 *= 2LL;
      v7 = realloc(v7, v4);
    }
    v7[i++] = v6;
    v6 = a2[i];
  }
  *a1 = v4;
  a1[1] = i;
  a1[2] = (size_t)v7;
  return a1;
}

//----- (0000000000001590) ----------------------------------------------------
size_t *__fastcall stralloc(size_t *a1, size_t a2)
{
  void *v4; // rax

  v4 = malloc(a2);
  if ( v4 == nullptr )
    stralloc_cold();
  a1[2] = (size_t)v4;
  *a1 = a2;
  a1[1] = 0;
  return a1;
}

//----- (00000000000015D0) ----------------------------------------------------
unsigned __int64 __fastcall straddc(unsigned __int64 *a1, char a2)
{
  unsigned __int64 v2; // rax
  unsigned __int64 v4; // rsi
  unsigned __int64 *v5; // rdx
  void *v6; // rdi
  unsigned __int64 result; // rax
  void *v8; // rax
  unsigned __int64 *v9; // [rsp+0h] [rbp-18h]
  char v10; // [rsp+Fh] [rbp-9h]

  v2 = a1[1];
  v4 = *a1;
  v5 = a1;
  v6 = (void *)a1[2];
  if ( v2 + 2 >= v4 )
  {
    v10 = a2;
    v9 = v5;
    v8 = realloc(v6, 2 * v4);
    v5 = v9;
    a2 = v10;
    v6 = v8;
    v9[2] = (unsigned __int64)v8;
    v2 = v9[1];
    *v9 *= 2LL;
  }
  *((_BYTE *)v6 + v2) = a2;
  result = v5[1];
  *(_BYTE *)(v5[2] + result + 1) = 0;
  ++v5[1];
  return result;
}

//----- (0000000000001640) ----------------------------------------------------
void __fastcall straddcs(_QWORD *a1, char *a2)
{
  char v2; // r12
  __int64 v3; // rdx
  char *v5; // rbp
  void *v6; // rdi
  void *v7; // rax

  v2 = *a2;
  if ( *a2 != 0 )
  {
    v3 = a1[1];
    v5 = a2;
    do
    {
      v6 = (void *)a1[2];
      if ( (unsigned __int64)(v3 + 2) >= *a1 )
      {
        v7 = realloc(v6, 2LL * *a1);
        v3 = a1[1];
        *a1 *= 2LL;
        a1[2] = v7;
        v6 = v7;
      }
      *((_BYTE *)v6 + v3) = v2;
      ++v5;
      *(_BYTE *)(a1[2] + a1[1] + 1LL) = 0;
      v3 = a1[1] + 1LL;
      a1[1] = v3;
      v2 = *v5;
    }
    while ( *v5 != 0 );
  }
}

//----- (00000000000016F0) ----------------------------------------------------
void __fastcall stradds(
        _QWORD *a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        int a7,
        int a8,
        char *a9)
{
  char *v9; // r12
  char v10; // bp
  __int64 v11; // rdx
  void *v13; // rdi
  void *v14; // rax

  v9 = a9;
  v10 = *a9;
  if ( *a9 != 0 )
  {
    v11 = a1[1];
    do
    {
      v13 = (void *)a1[2];
      if ( (unsigned __int64)(v11 + 2) >= *a1 )
      {
        v14 = realloc(v13, 2LL * *a1);
        v11 = a1[1];
        *a1 *= 2LL;
        a1[2] = v14;
        v13 = v14;
      }
      *((_BYTE *)v13 + v11) = v10;
      ++v9;
      *(_BYTE *)(a1[2] + a1[1] + 1LL) = 0;
      v11 = a1[1] + 1LL;
      a1[1] = v11;
      v10 = *v9;
    }
    while ( *v9 != 0 );
  }
}

//----- (00000000000017B0) ----------------------------------------------------
void __fastcall strfree(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, void *ptr)
{
  free(ptr);
}

//----- (00000000000017C0) ----------------------------------------------------
__int64 __fastcall strascstr(
        __int64 a1,
        __int64 a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        int a7,
        int a8,
        __int64 a9)
{
  return a9;
}

//----- (00000000000017D0) ----------------------------------------------------
void *__fastcall _base_vec_push(void **a1, __int64 *a2, __int64 *a3, size_t a4, const void *a5)
{
  __int64 v6; // rdx
  __int64 v7; // rax
  char *v10; // rdi
  __int64 v11; // rsi
  char *v12; // rax
  void *result; // rax
  const char *v14; // r8
  int v15; // ecx
  size_t v16; // [rsp+8h] [rbp-20h]
  void **v17; // [rsp+10h] [rbp-18h]
  const void *v18; // [rsp+18h] [rbp-10h]

  v6 = *a2;
  v7 = *a3;
  if ( *a3 < (unsigned __int64)*a2 )
  {
    v14 = "__base_vec_push: Possible memory corruption or vector not initialized, `Vector vector = {0}`";
    v15 = 75;
    goto LABEL_11;
  }
  v10 = (char *)*a1;
  if ( v6 != 0 )
  {
    if ( v10 != nullptr )
    {
      v11 = 2 * v6;
      if ( v6 != v7 )
        goto LABEL_6;
      goto LABEL_5;
    }
    v14 = "__base_vec_push: Possible memory corruption, data should be NULL only if length == 0";
    v15 = 76;
LABEL_11:
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/base.c", v15, v14);
    exit(1);
  }
  if ( v7 == 0 )
  {
    v11 = 128;
LABEL_5:
    *a3 = v11;
    v18 = a5;
    v17 = a1;
    v16 = a4;
    v12 = (char *)realloc(v10, a4 * v11);
    v6 = *a2;
    a5 = v18;
    a4 = v16;
    v10 = v12;
    *v17 = v12;
  }
LABEL_6:
  result = memcpy(&v10[a4 * v6], a5, a4);
  ++*a2;
  return result;
}

//----- (00000000000018A0) ----------------------------------------------------
__int64 __fastcall _base_vec_pop(__int64 a1, __int64 *a2, __int64 a3)
{
  __int64 v4; // rdx

  if ( *a2 == 0 )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/base.c", 92, "__base_vec_pop: Cannot pop from empty vector");
    exit(1);
  }
  v4 = *a2 - 1;
  *a2 = v4;
  return a1 + a3 * v4;
}

//----- (00000000000018F0) ----------------------------------------------------
void *__fastcall _base_vec_insert(
        void **a1,
        unsigned __int64 *a2,
        __int64 *a3,
        size_t a4,
        const void *a5,
        unsigned __int64 a6)
{
  unsigned __int64 v7; // rdx
  __int64 v8; // rax
  char *v11; // rdi
  size_t v12; // r10
  void *result; // rax
  __int64 v14; // rsi
  char *v15; // rax
  size_t v16; // [rsp+8h] [rbp-30h]
  size_t v17; // [rsp+8h] [rbp-30h]
  const void *v18; // [rsp+10h] [rbp-28h]
  size_t v19; // [rsp+10h] [rbp-28h]
  unsigned __int64 v20; // [rsp+18h] [rbp-20h]
  const void *v21; // [rsp+18h] [rbp-20h]

  v7 = *a2;
  if ( *a2 < a6 )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/base.c", 98, "__base_vec_insert: Index out of bounds for insertion");
    exit(1);
  }
  v8 = *a3;
  v11 = (char *)*a1;
  if ( v7 < *a3 )
  {
    v12 = a4 * a6;
    if ( a6 >= v7 )
      goto LABEL_4;
LABEL_8:
    v21 = a5;
    v19 = v12;
    v17 = a4;
    memmove(&v11[a4 + v12], &v11[v12], a4 * (v7 - a6));
    v11 = (char *)*a1;
    a5 = v21;
    v12 = v19;
    a4 = v17;
    goto LABEL_4;
  }
  v14 = 2 * v8;
  v20 = a6;
  if ( v8 == 0 )
    v14 = 2;
  v18 = a5;
  v16 = a4;
  *a3 = v14;
  v15 = (char *)realloc(v11, a4 * v14);
  a6 = v20;
  a4 = v16;
  v7 = *a2;
  a5 = v18;
  *a1 = v15;
  v11 = v15;
  v12 = v16 * v20;
  if ( v20 < v7 )
    goto LABEL_8;
LABEL_4:
  result = memcpy(&v11[v12], a5, a4);
  ++*a2;
  return result;
}

//----- (0000000000001A00) ----------------------------------------------------
__int64 __fastcall _base_vec_at(_QWORD *a1, unsigned __int64 *a2, unsigned __int64 a3, __int64 a4)
{
  if ( a3 >= *a2 )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/base.c", 115, "__base_vec_at: Index out of bounds");
    exit(1);
  }
  return a4 * a3 + *a1;
}

//----- (0000000000001A50) ----------------------------------------------------
void __fastcall _base_vec_free(void **a1, _QWORD *a2, _QWORD *a3)
{
  free(*a1);
  *a1 = nullptr;
  *a2 = 0;
  *a3 = 0;
}

//----- (0000000000001A90) ----------------------------------------------------
bool __fastcall issep(char a1)
{
  return strchr("[],.:\"'$", a1) != nullptr;
}

//----- (0000000000001AB0) ----------------------------------------------------
bool __fastcall isop(char a1)
{
  return strchr("+-/*", a1) != nullptr;
}

//----- (0000000000001AD0) ----------------------------------------------------
__int64 __fastcall isword(char a1)
{
  const unsigned __int16 **v2; // rax
  int v3; // edx

  v2 = __ctype_b_loc();
  v3 = a1;
  LOBYTE(v3) = a1 == 95;
  return v3 | (unsigned int)(((*v2)[a1] & 0x400) != 0);
}

//----- (0000000000001B00) ----------------------------------------------------
_BOOL8 __fastcall isnumber(char a1)
{
  return ((*__ctype_b_loc())[a1] & 0x800) != 0;
}

//----- (0000000000001B20) ----------------------------------------------------
bool __fastcall isnewline(char a1)
{
  return a1 == 10;
}

//----- (0000000000001B30) ----------------------------------------------------
__int64 __fastcall iswhitespace(char a1)
{
  return (a1 != 10) & (unsigned __int8)(HIBYTE((*__ctype_b_loc())[a1]) >> 5);
}

//----- (0000000000001B60) ----------------------------------------------------
bool __fastcall iscomment(char a1)
{
  return a1 == 59;
}

//----- (0000000000001B70) ----------------------------------------------------
bool __fastcall isnotquote(char a1)
{
  return a1 != 34;
}

//----- (0000000000001B80) ----------------------------------------------------
bool __fastcall isnotnewline(char a1)
{
  return a1 != 10;
}

//----- (0000000000001B90) ----------------------------------------------------
__int64 __fastcall exhaust(
        __int64 a1,
        __m128i *a2,
        unsigned __int64 *a3,
        __int64 (__fastcall *a4)(_QWORD),
        int a5,
        __int64 a6,
        int a7,
        unsigned __int64 a8,
        __int64 a9)
{
  char i; // al
  unsigned __int64 v14; // rax
  __m128i v15; // xmm0
  __int64 v16; // rax

  if ( *a3 < a8 )
  {
    for ( i = a4((unsigned int)*(char *)(a9 + *a3)); i != 0; i = a4((unsigned int)*(char *)(a9 + v14)) )
    {
      straddc((unsigned __int64 *)a2, *(_BYTE *)(a9 + *a3));
      v14 = *a3 + 1;
      *a3 = v14;
      if ( v14 >= a8 )
        break;
    }
  }
  v15 = _mm_loadu_si128(a2);
  *(_DWORD *)a1 = a5;
  v16 = a2[1].m128i_i64[0];
  *(__m128i *)(a1 + 8) = v15;
  *(_QWORD *)(a1 + 24) = v16;
  return a1;
}

//----- (0000000000001C50) ----------------------------------------------------
__int64 __fastcall next_token(
        __int64 a1,
        unsigned __int64 *a2,
        __int64 a3,
        __int64 a4,
        __int64 a5,
        __int64 a6,
        int a7,
        unsigned __int64 a8,
        __int64 a9)
{
  unsigned __int64 v10; // rbx
  char *v11; // r14
  char v12; // r15
  const unsigned __int16 **v13; // rax
  int v14; // edx
  int v15; // edi
  int v16; // r8d
  int v17; // r9d
  const unsigned __int16 *v18; // rcx
  const unsigned __int16 **v19; // rbp
  unsigned __int16 v20; // ax
  __int64 v21; // rax
  _BYTE *v22; // rax
  __m128i v23; // xmm0
  int v25; // esi
  __int64 v26; // rax
  __m128i v27; // xmm0
  __m128i v28; // xmm0
  void *v29; // rax
  _BYTE *v30; // rax
  __m128i si128; // xmm0
  __m128i v32; // xmm0
  void *v33; // rax
  __m128i v34; // xmm0
  void *v35; // rax
  __m128i v36; // xmm0
  void *v37; // rax
  int v38; // ecx
  __m128i v39; // [rsp+0h] [rbp-B8h]
  int v41[4]; // [rsp+30h] [rbp-88h] BYREF
  void *ptr; // [rsp+40h] [rbp-78h]
  _DWORD v43[6]; // [rsp+50h] [rbp-68h] BYREF
  __int64 v44; // [rsp+68h] [rbp-50h]
  unsigned __int64 v45; // [rsp+78h] [rbp-40h]

  v45 = __readfsqword(0x28u);
  stralloc((size_t *)v41, 8u);
  v10 = *a2;
  v11 = (char *)(a9 + *a2);
  while ( 1 )
  {
    if ( v10 >= a8 )
    {
      *(_OWORD *)(a1 + 4) = 0;
      *(_DWORD *)a1 = 8;
      *(_OWORD *)(a1 + 16) = 0;
      return a1;
    }
    v12 = *v11;
    if ( *v11 == 34 )
    {
      v30 = ptr;
      si128 = _mm_load_si128((const __m128i *)v41);
      *a2 = v10 + 1;
      if ( v30[v10] != 34 )
      {
        *(_DWORD *)a1 = 2;
        *(_QWORD *)(a1 + 24) = v30;
        *(__m128i *)(a1 + 8) = si128;
        return a1;
      }
      v38 = 69;
      goto LABEL_39;
    }
    if ( v12 == 59 )
    {
      do
      {
        if ( *(_BYTE *)(a9 + v10) == 10 )
          break;
        straddc((unsigned __int64 *)v41, *(_BYTE *)(a9 + v10));
        v10 = *a2 + 1;
        *a2 = v10;
      }
      while ( v10 < a8 );
      v22 = ptr;
      v23 = _mm_load_si128((const __m128i *)v41);
      *a2 = v10 + 1;
      if ( v22[v10] != 10 )
      {
        *(_DWORD *)a1 = 7;
        *(_QWORD *)(a1 + 24) = v22;
        *(__m128i *)(a1 + 8) = v23;
        return a1;
      }
      v38 = 77;
LABEL_39:
      printf("[%s] `%s`@%d: %s\n", "ERROR", "src/lexer.c", v38, "Closing \" was not found");
      exit(1);
    }
    v13 = __ctype_b_loc();
    v18 = *v13;
    v19 = v13;
    v20 = (*v13)[v12];
    if ( (v20 & 0x400) != 0 || v12 == 95 )
      break;
    if ( (v20 & 0x2000) != 0 && v12 != 10 )
    {
      while ( 1 )
      {
        v26 = *(char *)(a9 + v10);
        v25 = *(char *)(a9 + v10);
        if ( (v18[v26] & 0x2000) == 0 )
          break;
        if ( (_BYTE)v26 == 10 )
          break;
        straddc((unsigned __int64 *)v41, v25);
        v10 = *a2 + 1;
        *a2 = v10;
        if ( v10 >= a8 )
          break;
        v18 = *v19;
      }
      v39 = _mm_load_si128((const __m128i *)v41);
      strfree(v15, v25, v14, (int)v18, v16, v17, v39.m128i_i32[0], v39.m128i_i32[2], ptr);
      v43[0] = 6;
      *(_OWORD *)&v43[2] = 0;
      v27 = _mm_load_si128((const __m128i *)v43);
      v44 = 0;
      *(__m128i *)a1 = v27;
      *(__m128i *)(a1 + 16) = _mm_load_si128((const __m128i *)&v43[4]);
      return a1;
    }
    if ( (v20 & 0x800) != 0 )
    {
      while ( (v18[*(char *)(a9 + v10)] & 0x800) != 0 )
      {
        straddc((unsigned __int64 *)v41, *(_BYTE *)(a9 + v10));
        v10 = *a2 + 1;
        *a2 = v10;
        if ( v10 >= a8 )
          break;
        v18 = *v19;
      }
      v28 = _mm_load_si128((const __m128i *)v41);
      v29 = ptr;
      *(_DWORD *)a1 = 3;
      *(_QWORD *)(a1 + 24) = v29;
      *(__m128i *)(a1 + 8) = v28;
      return a1;
    }
    if ( strchr("+-/*", v12) != nullptr )
    {
      straddc((unsigned __int64 *)v41, v12);
      v34 = _mm_load_si128((const __m128i *)v41);
      v35 = ptr;
      ++*a2;
      *(_DWORD *)a1 = 4;
      *(_QWORD *)(a1 + 24) = v35;
      *(__m128i *)(a1 + 8) = v34;
      return a1;
    }
    if ( strchr("[],.:\"'$", v12) != nullptr )
    {
      straddc((unsigned __int64 *)v41, v12);
      v36 = _mm_load_si128((const __m128i *)v41);
      v37 = ptr;
      ++*a2;
      *(_DWORD *)a1 = 5;
      *(_QWORD *)(a1 + 24) = v37;
      *(__m128i *)(a1 + 8) = v36;
      return a1;
    }
    if ( v12 == 10 )
    {
      *a2 = v10 + 1;
      *(_OWORD *)a1 = 0;
      *(_OWORD *)(a1 + 16) = 0;
      return a1;
    }
  }
  while ( 1 )
  {
    v21 = *(char *)(a9 + v10);
    if ( (v18[v21] & 0x400) == 0 && (_BYTE)v21 != 95 )
      break;
    straddc((unsigned __int64 *)v41, *(_BYTE *)(a9 + v10));
    v10 = *a2 + 1;
    *a2 = v10;
    if ( v10 >= a8 )
      break;
    v18 = *v19;
  }
  v32 = _mm_load_si128((const __m128i *)v41);
  v33 = ptr;
  *(_DWORD *)a1 = 1;
  *(_QWORD *)(a1 + 24) = v33;
  *(__m128i *)(a1 + 8) = v32;
  return a1;
}
// 1E7E: variable 'v15' is possibly undefined
// 1E7E: variable 'v25' is possibly undefined
// 1E7E: variable 'v14' is possibly undefined
// 1E7E: variable 'v18' is possibly undefined
// 1E7E: variable 'v16' is possibly undefined
// 1E7E: variable 'v17' is possibly undefined

//----- (0000000000002060) ----------------------------------------------------
bool __fastcall isinstsplit(char a1)
{
  return strchr("\n;", a1) != nullptr;
}

//----- (0000000000002080) ----------------------------------------------------
bool __fastcall isopsplit(char a1)
{
  return strchr(",", a1) != nullptr;
}

//----- (00000000000020A0) ----------------------------------------------------
void __fastcall skip_whitespace(__int64 a1, __int64 *a2, _BYTE *a3)
{
  const unsigned __int16 **v6; // rdx
  __int64 v7; // rax
  __int64 v8; // rbx

  if ( *a3 == 0 )
  {
    while ( 1 )
    {
      v8 = *a2;
      if ( (unsigned __int64)*a2 >= *(_QWORD *)(a1 + 8) )
        break;
      v6 = __ctype_b_loc();
      v7 = *(_QWORD *)(a1 + 16);
      if ( ((*v6)[*(char *)(v7 + v8)] & 0x2000) == 0 )
        break;
      *a2 = v8 + 1;
      if ( strchr("\n;", *(char *)(v7 + v8 + 1)) != nullptr )
      {
        *a3 = 1;
        return;
      }
    }
  }
}

//----- (0000000000002130) ----------------------------------------------------
unsigned __int64 __fastcall skip_until_newline(__int64 a1, unsigned __int64 *a2)
{
  unsigned __int64 result; // rax
  __int64 v3; // rcx

  for ( result = *a2; result < *(_QWORD *)(a1 + 8); ++result )
  {
    v3 = *(_QWORD *)(a1 + 16);
    *a2 = result + 1;
    if ( *(_BYTE *)(v3 + result) == 10 )
      goto LABEL_6;
  }
  --result;
LABEL_6:
  *a2 = result;
  return result;
}

//----- (0000000000002170) ----------------------------------------------------
unsigned __int64 *__fastcall collect_symbol(__int64 a1, unsigned __int64 *a2, _BYTE *a3)
{
  __int64 v3; // r12
  __int64 v4; // r14
  unsigned __int64 v7; // rbx
  __int64 v8; // r14
  __int64 v9; // r12
  int v10; // ebp
  char *v12; // rax
  unsigned __int64 v13; // rbx
  unsigned __int64 *v14; // [rsp+8h] [rbp-80h]
  __m128i v16; // [rsp+20h] [rbp-68h] BYREF
  unsigned __int64 v17; // [rsp+30h] [rbp-58h]
  unsigned __int64 v18; // [rsp+48h] [rbp-40h]
  __int64 v19; // [rsp+68h] [rbp-20h]
  __int64 v20; // [rsp+78h] [rbp-10h]

  v18 = __readfsqword(0x28u);
  v14 = (unsigned __int64 *)malloc(0x18u);
  if ( v14 == nullptr )
  {
    v19 = v3;
    v20 = v4;
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/parser.c", 42, "instruction allocation failed");
    exit(1);
  }
  stralloc((size_t *)&v16, 0x14u);
  v7 = *a2;
  *(__m128i *)v14 = _mm_loadu_si128(&v16);
  v14[2] = v17;
  if ( v7 >= *(_QWORD *)(a1 + 8) )
    goto LABEL_9;
  v19 = v3;
  while ( 1 )
  {
    v8 = *(_QWORD *)(a1 + 16);
    v9 = *(char *)(v8 + v7);
    if ( strchr("\n;", *(char *)(v8 + v7)) != nullptr )
    {
LABEL_8:
      v3 = v19;
LABEL_9:
      if ( v14[1] != 0 )
      {
        v8 = *(_QWORD *)(a1 + 16);
        v10 = *(char *)(v8 + v7);
        if ( strchr(",", v10) == nullptr )
        {
          v12 = strchr("\n;", v10);
          goto LABEL_18;
        }
        goto LABEL_11;
      }
      v19 = v3;
      goto LABEL_27;
    }
    if ( strchr(",", v9) != nullptr )
    {
      if ( v14[1] != 0 )
      {
        v3 = v19;
LABEL_11:
        *a2 = v7 + 1;
        goto LABEL_12;
      }
LABEL_27:
      printf("[%s] `%s`@%d: %s\n", "ERROR", "src/parser.c", 55, "found ',' or ';' while looking for operand");
      exit(1);
    }
    if ( ((*__ctype_b_loc())[v9] & 0x2000) != 0 )
      break;
    straddc(v14, v9);
    v7 = *a2 + 1;
    *a2 = v7;
    if ( v7 >= *(_QWORD *)(a1 + 8) )
      goto LABEL_8;
  }
  if ( v14[1] == 0 )
    goto LABEL_27;
  v3 = v19;
  v12 = strchr("\n;", *(char *)(v8 + v7));
LABEL_18:
  if ( v12 != nullptr )
  {
    v13 = v7 + 1;
    *a2 = v13;
    while ( v13 < *(_QWORD *)(a1 + 8) )
    {
      *a2 = v13 + 1;
      if ( *(_BYTE *)(v8 + v13) == 10 )
        goto LABEL_24;
      ++v13;
    }
    --v13;
LABEL_24:
    *a2 = v13;
    *a3 = 1;
  }
LABEL_12:
  if ( v18 != __readfsqword(0x28u) )
    v19 = v3;
  return v14;
}
// 2170: could not find valid save-restore pair for r12
// 21FF: variable 'v3' is possibly undefined
// 23F7: variable 'v4' is possibly undefined

//----- (0000000000002420) ----------------------------------------------------
__int64 __fastcall next_inst(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r14
  __int64 v6; // rbp
  unsigned __int64 *v8; // rax
  unsigned __int64 *v9; // r14
  unsigned __int64 *v10; // rax
  void *v11; // rax
  __int64 v12; // rax
  __int64 v13[2]; // [rsp+8h] [rbp-60h] BYREF
  char v14; // [rsp+1Fh] [rbp-49h] BYREF
  __int128 v15; // [rsp+20h] [rbp-48h] BYREF
  void *v16; // [rsp+30h] [rbp-38h] BYREF
  unsigned __int64 v17; // [rsp+38h] [rbp-30h]
  __int64 v18; // [rsp+60h] [rbp-8h]

  v13[0] = a2;
  v17 = __readfsqword(0x28u);
  v14 = 0;
  v16 = nullptr;
  v15 = 0;
  skip_whitespace(a1, v13, &v14);
  v6 = v13[0] + 1;
  if ( strchr("\n;", *(char *)(*(_QWORD *)(a1 + 16) + v13[0] + 1)) == nullptr && v14 == 0 )
  {
    v18 = v3;
    v8 = collect_symbol(a1, (unsigned __int64 *)v13, &v14);
    v9 = v8;
    if ( v14 != 0 )
    {
      *(_QWORD *)a3 = v8;
      v12 = v13[0];
      *(_BYTE *)(a3 + 16) = 0;
      v3 = v18;
      *(_QWORD *)(a3 + 8) = 0;
      v6 = v12 + 1;
    }
    else
    {
      while ( 1 )
      {
        v6 = v13[0];
        if ( v13[0] >= *(_QWORD *)(a1 + 8) )
          break;
        skip_whitespace(a1, v13, &v14);
        if ( v14 != 0 )
          goto LABEL_12;
        v10 = collect_symbol(a1, (unsigned __int64 *)v13, &v14);
        if ( v10[1] != 0 )
        {
          _base_vec_push(&v16, (__int64 *)&v15 + 1, (__int64 *)&v15, 0x18u, v10);
          if ( v14 != 0 )
          {
LABEL_12:
            v6 = v13[0];
            break;
          }
        }
        else if ( v14 != 0 )
        {
          goto LABEL_12;
        }
      }
      v11 = v16;
      *(_QWORD *)a3 = v9;
      *(_QWORD *)(a3 + 8) = v11;
      *(_BYTE *)(a3 + 16) = BYTE8(v15);
      v3 = v18;
    }
  }
  if ( v17 != __readfsqword(0x28u) )
    v18 = v3;
  return v6;
}
// 2420: could not find valid save-restore pair for r14
// 24D4: variable 'v3' is possibly undefined

//----- (00000000000025C0) ----------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  ;
}

// nfuncs=75 queued=40 decompiled=40 lumina nreq=0 worse=0 better=0
// ALL OK, 40 function(s) have been successfully decompiled
