/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// void free(void *ptr);
// size_t fread(void *ptr, size_t size, size_t n, FILE *stream);
// size_t strlen(const char *s);
// char *strchr(const char *s, int c);
// int printf(const char *format, ...);
// void *memcpy(void *dest, const void *src, size_t n);
// void *malloc(size_t size);
// int fflush(FILE *stream);
// void *realloc(void *ptr, size_t size);
// void *memmove(void *dest, const void *src, size_t n);
// FILE *fopen(const char *filename, const char *modes);
// void perror(const char *s);
// void __noreturn exit(int status);
// const unsigned __int16 **__ctype_b_loc(void);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
FILE **deregister_tm_clones();
__int64 register_tm_clones();
FILE **_do_global_dtors_aux();
__int64 frame_dummy(); // weak
string_t *__fastcall cstrasstr(string_t *__return_ptr retstr, char *cstr);
string_t *__fastcall stralloc(string_t *__return_ptr retstr, uint64_t capacity); // idb
void __fastcall straddc(string_t *str, char c); // idb
void __fastcall straddcs(string_t *str, char *cstr);
void __fastcall stradds(string_t *str, string_t other); // idb
void __cdecl strfree(string_t str);
const char *__cdecl strascstr(string_t str);
void __fastcall _base_vec_push(void **data, size_t *length, size_t *capacity, size_t element_size, void *value); // idb
char *__fastcall _base_vec_pop(char *data, size_t *length, size_t element_size);
void __fastcall _base_vec_insert(void **data, size_t *length, size_t *capacity, size_t element_size, void *value, size_t index); // idb
char *__fastcall _base_vec_at(void **data, size_t *length, size_t index, size_t elementSize);
void __fastcall _base_vec_free(void **data, size_t *length, size_t *capacity); // idb
bool __fastcall issep(char c); // idb
bool __fastcall isop(char c); // idb
_BOOL8 __fastcall isword(char c);
_BOOL8 __fastcall isnumber(char c);
bool __fastcall isnewline(char c); // idb
_BOOL8 __fastcall iswhitespace(char c);
bool __fastcall iscomment(char c); // idb
bool __fastcall isnotquote(char c); // idb
_BOOL8 __fastcall isnotnewline(char c);
token_t *__fastcall exhaust(token_t *__return_ptr retstr, string_t *tvalue, uint64_t *offset, bool (*ismatch)(char), tokentype_t type, string_t text);
token_t *__fastcall next_token(token_t *__return_ptr retstr, uint64_t *offset, string_t text);
int __fastcall main(int argc, const char **argv, const char **envp);
bool __fastcall isinstsplit(char c); // idb
bool __fastcall isopsplit(char c); // idb
void __fastcall skip_whitespace(string_t *s, uint64_t *offset, bool *hitend); // idb
void __fastcall skip_until_newline(string_t *s, uint64_t *offset); // idb
string_t *__fastcall collect_symbol(string_t *s, uint64_t *offset, bool *hitend); // idb
uint64_t __fastcall next_inst(string_t *s, uint64_t offset, instruction_t *inst); // idb
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int _cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak
// __int64 ITM_registerTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

void *_dso_handle = &_dso_handle; // idb
FILE *stdout; // idb
char completed_0; // weak


//----- (0000000000001000) ----------------------------------------------------
// Alternative name is '_init'
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ != nullptr )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 5130: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001120) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, nullptr, nullptr, a3, &v5);
  __halt();
}
// 112A: positive sp value 8 has been found
// 1131: variable 'v3' is possibly undefined

//----- (0000000000001150) ----------------------------------------------------
FILE **deregister_tm_clones()
{
  return &stdout;
}
// 5128: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (0000000000001180) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0;
}
// 5138: using guessed type __int64 ITM_registerTMCloneTable(void);

//----- (00000000000011C0) ----------------------------------------------------
FILE **_do_global_dtors_aux()
{
  FILE **result; // rax

  if ( completed_0 == 0 )
  {
    if ( &_cxa_finalize != nullptr )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 5090: using guessed type char completed_0;

//----- (0000000000001210) ----------------------------------------------------
__int64 frame_dummy()
{
  return register_tm_clones();
}
// 1210: using guessed type __int64 frame_dummy();

//----- (0000000000001219) ----------------------------------------------------
string_t *__fastcall cstrasstr(string_t *__return_ptr retstr, char *cstr)
{
  size_t len; // [rsp+18h] [rbp-28h]
  string_t str; // [rsp+20h] [rbp-20h] BYREF
  unsigned __int64 v7; // [rsp+38h] [rbp-8h]

  v7 = __readfsqword(0x28u);
  len = strlen(cstr);
  stralloc(&str, len + 1);
  straddcs(&str, cstr);
  *retstr = str;
  return retstr;
}

//----- (00000000000012A7) ----------------------------------------------------
string_t *__fastcall stralloc(string_t *__return_ptr retstr, uint64_t capacity)
{
  char *ptr; // [rsp+18h] [rbp-28h]

  ptr = (char *)malloc(capacity);
  if ( ptr == nullptr )
  {
    perror("stralloc, ptr allocation failed");
    exit(1);
  }
  retstr->capacity = capacity;
  retstr->length = 0;
  retstr->ptr = ptr;
  return retstr;
}

//----- (0000000000001320) ----------------------------------------------------
void __fastcall straddc(string_t *str, char c)
{
  if ( str->length + 2 >= str->capacity )
  {
    str->ptr = (char *)realloc(str->ptr, 2 * str->capacity);
    str->capacity *= 2LL;
  }
  str->ptr[str->length] = c;
  str->ptr[++str->length] = 0;
}

//----- (00000000000013CA) ----------------------------------------------------
void __fastcall straddcs(string_t *str, char *cstr)
{
  while ( *cstr != 0 )
    straddc(str, *cstr++);
}

//----- (0000000000001408) ----------------------------------------------------
void __fastcall stradds(string_t *str, string_t other)
{
  straddcs(str, other.ptr);
}

//----- (000000000000142A) ----------------------------------------------------
void __cdecl strfree(string_t str)
{
  free(str.ptr);
}

//----- (000000000000143D) ----------------------------------------------------
const char *__cdecl strascstr(string_t str)
{
  return str.ptr;
}

//----- (0000000000001447) ----------------------------------------------------
void __fastcall _base_vec_push(void **data, size_t *length, size_t *capacity, size_t element_size, void *value)
{
  if ( *capacity < *length )
  {
    printf(
      "[%s] `%s`@%d: %s\n",
      "ERROR",
      "src/base.c",
      75,
      "__base_vec_push: Possible memory corruption or vector not initialized, `Vector vector = {0}`");
    exit(1);
  }
  if ( *length != 0 && *data == nullptr )
  {
    printf(
      "[%s] `%s`@%d: %s\n",
      "ERROR",
      "src/base.c",
      76,
      "__base_vec_push: Possible memory corruption, data should be NULL only if length == 0");
    exit(1);
  }
  if ( *length >= *capacity )
  {
    if ( *capacity != 0 )
      *capacity *= 2LL;
    else
      *capacity = 128;
    *data = realloc(*data, element_size * *capacity);
  }
  memcpy((char *)*data + element_size * *length, value, element_size);
  ++*length;
}

//----- (00000000000015B0) ----------------------------------------------------
char *__fastcall _base_vec_pop(char *data, size_t *length, size_t element_size)
{
  if ( *length == 0 )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/base.c", 92, "__base_vec_pop: Cannot pop from empty vector");
    exit(1);
  }
  --*length;
  return &data[element_size * *length];
}

//----- (0000000000001635) ----------------------------------------------------
void __fastcall _base_vec_insert(
        void **data,
        size_t *length,
        size_t *capacity,
        size_t element_size,
        void *value,
        size_t index)
{
  if ( *length < index )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/base.c", 98, "__base_vec_insert: Index out of bounds for insertion");
    exit(1);
  }
  if ( *length >= *capacity )
  {
    if ( *capacity != 0 )
      *capacity *= 2LL;
    else
      *capacity = 2;
    *data = realloc(*data, element_size * *capacity);
  }
  if ( index < *length )
    memmove(
      (char *)*data + element_size * (index + 1),
      (char *)*data + element_size * index,
      element_size * (*length - index));
  memcpy((char *)*data + element_size * index, value, element_size);
  ++*length;
}

//----- (0000000000001792) ----------------------------------------------------
char *__fastcall _base_vec_at(void **data, size_t *length, size_t index, size_t elementSize)
{
  if ( index >= *length )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/base.c", 115, "__base_vec_at: Index out of bounds");
    exit(1);
  }
  return (char *)*data + elementSize * index;
}

//----- (000000000000180F) ----------------------------------------------------
void __fastcall _base_vec_free(void **data, size_t *length, size_t *capacity)
{
  free(*data);
  *data = nullptr;
  *length = 0;
  *capacity = 0;
}

//----- (0000000000001856) ----------------------------------------------------
bool __fastcall issep(char c)
{
  return strchr("[],.:\"'$", c) != nullptr;
}

//----- (000000000000187F) ----------------------------------------------------
bool __fastcall isop(char c)
{
  return strchr("+-/*", c) != nullptr;
}

//----- (00000000000018A8) ----------------------------------------------------
_BOOL8 __fastcall isword(char c)
{
  return ((*__ctype_b_loc())[c] & 0x400) != 0 || c == 95;
}

//----- (00000000000018ED) ----------------------------------------------------
_BOOL8 __fastcall isnumber(char c)
{
  return ((*__ctype_b_loc())[c] & 0x800) != 0;
}

//----- (000000000000191F) ----------------------------------------------------
bool __fastcall isnewline(char c)
{
  return c == 10;
}

//----- (0000000000001930) ----------------------------------------------------
_BOOL8 __fastcall iswhitespace(char c)
{
  return ((*__ctype_b_loc())[c] & 0x2000) != 0 && !isnewline(c);
}

//----- (0000000000001981) ----------------------------------------------------
bool __fastcall iscomment(char c)
{
  return c == 59;
}

//----- (0000000000001992) ----------------------------------------------------
bool __fastcall isnotquote(char c)
{
  return c != 34;
}

//----- (00000000000019A3) ----------------------------------------------------
_BOOL8 __fastcall isnotnewline(char c)
{
  return !isnewline(c);
}

//----- (00000000000019CD) ----------------------------------------------------
token_t *__fastcall exhaust(
        token_t *__return_ptr retstr,
        string_t *tvalue,
        uint64_t *offset,
        bool (*ismatch)(char),
        tokentype_t type,
        string_t text)
{
  size_t length; // rdx

  while ( *offset < text.length && ismatch(text.ptr[*offset]) )
  {
    straddc(tvalue, text.ptr[*offset]);
    ++*offset;
  }
  retstr->type = type;
  length = tvalue->length;
  retstr->value.capacity = tvalue->capacity;
  retstr->value.length = length;
  retstr->value.ptr = tvalue->ptr;
  return retstr;
}

//----- (0000000000001A7D) ----------------------------------------------------
token_t *__fastcall next_token(token_t *__return_ptr retstr, uint64_t *offset, string_t text)
{
  char *ptr; // rsi
  uint64_t v4; // rax
  size_t capacity; // rdx
  char *v6; // rdx
  char *v7; // rsi
  uint64_t v8; // rax
  char *v9; // rdx
  char current; // [rsp+1Fh] [rbp-51h]
  string_t tvalue; // [rsp+20h] [rbp-50h] BYREF
  token_t tok; // [rsp+40h] [rbp-30h] BYREF
  unsigned __int64 v16; // [rsp+68h] [rbp-8h]

  v16 = __readfsqword(0x28u);
  stralloc(&tvalue, 8u);
  while ( 1 )
  {
    if ( *offset >= text.length )
    {
      *(_OWORD *)&retstr->type = 0;
      *(_OWORD *)&retstr->value.length = 0;
      retstr->type = END;
      return retstr;
    }
    current = text.ptr[*offset];
    if ( current == 34 )
    {
      exhaust(&tok, &tvalue, offset, isnotquote, LITERAL, text);
      ptr = tvalue.ptr;
      v4 = (*offset)++;
      if ( ptr[v4] == 34 )
      {
        printf("[%s] `%s`@%d: %s\n", "ERROR", "src/lexer.c", 69, "Closing \" was not found");
        exit(1);
      }
LABEL_5:
      capacity = tok.value.capacity;
      *(_QWORD *)&retstr->type = *(_QWORD *)&tok.type;
      retstr->value.capacity = capacity;
      v6 = tok.value.ptr;
      retstr->value.length = tok.value.length;
      retstr->value.ptr = v6;
      return retstr;
    }
    if ( iscomment(current) )
    {
      exhaust(&tok, &tvalue, offset, (bool (*)(char))isnotnewline, COMMENT, text);
      v7 = tvalue.ptr;
      v8 = (*offset)++;
      if ( v7[v8] == 10 )
      {
        printf("[%s] `%s`@%d: %s\n", "ERROR", "src/lexer.c", 77, "Closing \" was not found");
        exit(1);
      }
      goto LABEL_5;
    }
    if ( isword(current) )
      break;
    if ( iswhitespace(current) )
    {
      exhaust(&tok, &tvalue, offset, (bool (*)(char))iswhitespace, WHITESPACE, text);
      strfree(tok.value);
      memset(&tok.value, 0, sizeof(tok.value));
      *(_QWORD *)&retstr->type = *(_QWORD *)&tok.type;
      retstr->value.capacity = 0;
      v9 = tok.value.ptr;
      retstr->value.length = tok.value.length;
      retstr->value.ptr = v9;
      return retstr;
    }
    if ( isnumber(current) )
    {
      exhaust(retstr, &tvalue, offset, (bool (*)(char))isnumber, NUMBER, text);
      return retstr;
    }
    if ( isop(current) )
    {
      straddc(&tvalue, current);
      ++*offset;
      retstr->type = OPERATOR;
      retstr->value = tvalue;
      return retstr;
    }
    if ( issep(current) )
    {
      straddc(&tvalue, current);
      ++*offset;
      retstr->type = SEPARATOR;
      retstr->value = tvalue;
      return retstr;
    }
    if ( isnewline(current) )
    {
      ++*offset;
      *(_OWORD *)&retstr->type = 0;
      *(_OWORD *)&retstr->value.length = 0;
      return retstr;
    }
  }
  exhaust(retstr, &tvalue, offset, (bool (*)(char))isword, WORD, text);
  return retstr;
}

//----- (0000000000001F28) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  const char *v3; // rax
  token_t v5; // [rsp+0h] [rbp-4D0h] BYREF
  uint64_t offset; // [rsp+28h] [rbp-4A8h] BYREF
  token_t *tok; // [rsp+30h] [rbp-4A0h]
  FILE *file; // [rsp+38h] [rbp-498h]
  string_t assembly; // [rsp+40h] [rbp-490h] BYREF
  __int128 tokens; // [rsp+60h] [rbp-470h] BYREF
  token_t *v11; // [rsp+70h] [rbp-460h] BYREF
  token_t it; // [rsp+80h] [rbp-450h] BYREF
  _QWORD as[4]; // [rsp+A0h] [rbp-430h] BYREF
  char buffer[1032]; // [rsp+C0h] [rbp-410h] BYREF
  unsigned __int64 v15; // [rsp+4C8h] [rbp-8h]

  v15 = __readfsqword(0x28u);
  stralloc(&assembly, 0x80u);
  file = fopen("./playground/mov.asm", "r");
  while ( fread(buffer, 1u, 0x400u, file) != 0 )
    straddcs(&assembly, buffer);
  offset = 0;
  tokens = 0;
  v11 = nullptr;
  next_token(&it, &offset, assembly);
  while ( it.type != END )
  {
    _base_vec_push((void **)&v11, (size_t *)&tokens + 1, (size_t *)&tokens, 0x20u, &it);
    next_token(&v5, &offset, assembly);
    it = v5;
  }
  strcpy((char *)as, "please help me in debug");
  printf("%s", (const char *)as);
  fflush(stdout);
  for ( tok = v11; v11 != nullptr && tok < &v11[*((_QWORD *)&tokens + 1)]; ++tok )
  {
    if ( tok->type != WHITESPACE && tok->type != END && tok->type != NEWLINE )
    {
      v3 = strascstr(tok->value);
      printf("[%s] `%s`@%d: %d: %s\n", "INFO", "src/main.c", 35, tok->type, v3);
    }
  }
  return 0;
}

//----- (000000000000223A) ----------------------------------------------------
bool __fastcall isinstsplit(char c)
{
  return strchr("\n;", c) != nullptr;
}

//----- (0000000000002263) ----------------------------------------------------
bool __fastcall isopsplit(char c)
{
  return strchr(",", c) != nullptr;
}

//----- (000000000000228C) ----------------------------------------------------
void __fastcall skip_whitespace(string_t *s, uint64_t *offset, bool *hitend)
{
  while ( !*hitend && *offset < s->length && ((*__ctype_b_loc())[s->ptr[*offset]] & 0x2000) != 0 )
  {
    if ( isinstsplit(s->ptr[++*offset]) )
      *hitend = true;
  }
}

//----- (000000000000233D) ----------------------------------------------------
void __fastcall skip_until_newline(string_t *s, uint64_t *offset)
{
  char *ptr; // rsi
  uint64_t v3; // rax

  do
  {
    if ( *offset >= s->length )
      break;
    ptr = s->ptr;
    v3 = (*offset)++;
  }
  while ( ptr[v3] != 10 );
  --*offset;
}

//----- (0000000000002397) ----------------------------------------------------
string_t *__fastcall collect_symbol(string_t *s, uint64_t *offset, bool *hitend)
{
  string_t *v3; // rbx
  string_t v5; // [rsp+0h] [rbp-60h] BYREF
  bool *hitenda; // [rsp+28h] [rbp-38h]
  uint64_t *offseta; // [rsp+30h] [rbp-30h]
  string_t *sa; // [rsp+38h] [rbp-28h]
  string_t *symbol; // [rsp+40h] [rbp-20h]
  unsigned __int64 v10; // [rsp+48h] [rbp-18h]

  sa = s;
  offseta = offset;
  hitenda = hitend;
  v10 = __readfsqword(0x28u);
  symbol = (string_t *)malloc(0x18u);
  if ( symbol == nullptr )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/parser.c", 42, "instruction allocation failed");
    exit(1);
  }
  v3 = symbol;
  stralloc(&v5, 0x14u);
  *v3 = v5;
  while ( *offseta < sa->length
       && !isinstsplit(sa->ptr[*offseta])
       && !isopsplit(sa->ptr[*offseta])
       && ((*__ctype_b_loc())[sa->ptr[*offseta]] & 0x2000) == 0 )
  {
    straddc(symbol, sa->ptr[*offseta]);
    ++*offseta;
  }
  if ( symbol->length == 0 )
  {
    printf("[%s] `%s`@%d: %s\n", "ERROR", "src/parser.c", 55, "found ',' or ';' while looking for operand");
    exit(1);
  }
  if ( isopsplit(sa->ptr[*offseta]) )
  {
    ++*offseta;
  }
  else if ( isinstsplit(sa->ptr[*offseta]) )
  {
    ++*offseta;
    skip_until_newline(sa, offseta);
    *hitenda = true;
  }
  return symbol;
}

//----- (00000000000025FB) ----------------------------------------------------
uint64_t __fastcall next_inst(string_t *s, uint64_t offset, instruction_t *inst)
{
  string_t *v4; // rdx
  uint8_t v5; // si
  uint64_t offseta; // [rsp+10h] [rbp-50h] BYREF
  string_t *sa; // [rsp+18h] [rbp-48h]
  bool hitend; // [rsp+2Fh] [rbp-31h] BYREF
  string_t *mnemonic; // [rsp+30h] [rbp-30h]
  string_t *operand; // [rsp+38h] [rbp-28h]
  __int128 operands; // [rsp+40h] [rbp-20h] BYREF
  void *v13[2]; // [rsp+50h] [rbp-10h] BYREF

  sa = s;
  offseta = offset;
  v13[1] = (void *)__readfsqword(0x28u);
  operands = 0;
  v13[0] = nullptr;
  hitend = false;
  skip_whitespace(s, &offseta, &hitend);
  if ( isinstsplit(sa->ptr[offseta + 1]) )
    hitend = true;
  if ( hitend )
    return offseta + 1;
  mnemonic = collect_symbol(sa, &offseta, &hitend);
  if ( hitend )
  {
    inst->mnemonic = mnemonic;
    inst->operands = nullptr;
    inst->opcount = 0;
    return ++offseta;
  }
  else
  {
    do
    {
      if ( offseta >= sa->length )
        break;
      skip_whitespace(sa, &offseta, &hitend);
      if ( hitend )
        break;
      operand = collect_symbol(sa, &offseta, &hitend);
      if ( operand->length != 0 )
        _base_vec_push(v13, (size_t *)&operands + 1, (size_t *)&operands, 0x18u, operand);
    }
    while ( !hitend );
    v4 = (string_t *)v13[0];
    v5 = BYTE8(operands);
    inst->mnemonic = mnemonic;
    inst->operands = v4;
    inst->opcount = v5;
    return offseta;
  }
}

//----- (00000000000027B0) ----------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  ;
}

// nfuncs=73 queued=38 decompiled=38 lumina nreq=0 worse=0 better=0
// ALL OK, 38 function(s) have been successfully decompiled
